using NUnit.Framework;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Unity.VisualScripting;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.UI;

public class ToolInGame : MonoBehaviour, IPointerEnterHandler, IPointerExitHandler
{
    public RectTransform rt;
    [SerializeField] private GameObject visibilityObject;
    [SerializeField] private Image toolImage;
    [SerializeField] private Label toolNameLabel;
    [SerializeField] private Label handStyleLabel;
    // [SerializeField] private RectTransform requiredCardsParent;
    [SerializeField] private ButtonPlus buttonPlus;
    public HandType handType;
    public int cardsRequired;
    private ToolTargetStyle toolTargetStyle;
    private int adjacentColumnsTarget = 0; // 1 means player can target column plus one column on each side etc
    private int areaOfEffectRadius = 0; // 1 means target plus adjacent tiles in all 4 cardinal directions
    private int damage;
    private ToolSpecialTag[] toolSpecialTags;
    private ToolInGame baseToolInGame;
    public Tool baseTool;
    private bool isBase; // the ones that get generated when you obtain a new tool
    private bool isUsable; // the ones that get dynamically generated by selecting cards
    private List<Card> cardsToSelectIfClicked = new List<Card>();
    public void SetVisibility(bool visible)
    {
        visibilityObject.SetActive(visible);
    }
    public void SetInteractability(bool interactable)
    {
        buttonPlus.SetButtonEnabled(interactable);
    }
    public void SetInteractabilityBasedOnAvailability()
    {
        if (cardsToSelectIfClicked != null && cardsToSelectIfClicked.Count > 0)
        {
            SetInteractability(true);
        }
        else
        {
            SetInteractability(false);
        }
    }
    public void SetupNewToolInGame(Tool newBaseTool)
    {
        baseToolInGame = null;
        baseTool = newBaseTool;
        toolImage.sprite = newBaseTool.toolIcon;
        toolNameLabel.ChangeText(newBaseTool.toolName);
        handStyleLabel.ChangeText(newBaseTool.GetHandStyleString());
        handType = baseTool.handStyle;
        cardsRequired = baseTool.cardsRequired;
        toolTargetStyle = baseTool.toolTargetStyle;
        adjacentColumnsTarget = baseTool.adjacentColumnsTarget;
        areaOfEffectRadius = baseTool.areaOfEffectRadius;
        damage = baseTool.damage;
        toolSpecialTags = baseTool.toolSpecialTags;
        isUsable = false;
        isBase = true;
        name = "ToolInGame_" + newBaseTool.toolName;
    }
    public void SetupFromToolInGame(ToolInGame toolInGame)
    {
        baseToolInGame = toolInGame;
        baseTool = toolInGame.baseTool;
        toolImage.sprite = toolInGame.toolImage.sprite;
        toolNameLabel.ChangeText(toolInGame.toolNameLabel.GetText());
        handStyleLabel.ChangeText(toolInGame.handStyleLabel.GetText());
        handType = baseToolInGame.handType;
        cardsRequired = baseToolInGame.cardsRequired;
        toolTargetStyle = baseToolInGame.toolTargetStyle;
        adjacentColumnsTarget = baseToolInGame.adjacentColumnsTarget;
        areaOfEffectRadius = baseToolInGame.areaOfEffectRadius;
        damage = baseToolInGame.damage;
        toolSpecialTags = baseToolInGame.toolSpecialTags;
        isUsable = true;
        isBase = false;
        name = "UsableToolInGame_" + toolInGame.baseTool.toolName;
    }
    public void Click()
    {
        if (isUsable)
        {
            if (toolTargetStyle == ToolTargetStyle.Self)
            {
                CombatManager.instance.ApplySelfTool(this);
            }
            else
            {
                bool aiming = HasSpecialTag(ToolSpecialTag.AlwaysAim);
                CombatManager.instance.SetTargetingTool(this, aiming);
            }
        }
        else if (isBase)
        {
            if (CombatManager.instance.inCombat)
            {
                HandArea.instance.SelectSpecificCards(cardsToSelectIfClicked);
                Tools.instance.AvailableToolSelected(this);
                // bool aiming = HasSpecialTag(ToolSpecialTag.AlwaysAim);
                // CombatManager.instance.SetTargetingTool(this, aiming);
            }
            else
            {
                Logger.instance.Log("Open context menu");
                
            }
        }
    }
    public void OnPointerEnter(PointerEventData pointerEventData)
    {
        PreviewSelectableTargets();
        DisplayTooltip(r.i.interf.GetCanvasPositionOfRectTransform(rt, GameManager.instance.gameplayCanvas) + new Vector2(0, rt.sizeDelta.y / 2 + 4f), TooltipAlignment.Bottom);
    }
    public void OnPointerExit(PointerEventData pointerEventData)
    {
        EndTargetPreview();
        Tooltip.instance.SetVisibility(false);
    }
    public void PreviewSelectableTargets()
    {
        if (CombatManager.instance.IsTargeting())
        {
            return;
        }
        if (toolTargetStyle == ToolTargetStyle.Self)
        {
            return;
        }
        bool aiming = HasSpecialTag(ToolSpecialTag.AlwaysAim);
    }
    public void EndTargetPreview()
    {
        if (CombatManager.instance.IsTargeting())
        {
            return;
        };
    }
    public int GetImpact()
    {
        return damage;
    }
    public int GetDamage( EnemyInGame affectedEnemy, bool aiming = false, LimbInGame targetedLimb = null)
    {
        int totalDamage = damage;
        
        return totalDamage;
    }
    public int GetAreaOfEffect()
    {
        return areaOfEffectRadius;
    }
    public bool HasSpecialTag(ToolSpecialTag toolSpecialTag)
    {
        return toolSpecialTags.Contains(toolSpecialTag);
    }
    public int GetAdjacentColumnsTarget()
    {
        return adjacentColumnsTarget;
    }
    public int GetAreaOfEffectRadius()
    {
        return areaOfEffectRadius;
    }
    public ToolTargetStyle GetToolTargetStyle()
    {
        return toolTargetStyle;
    }
    public string GetToolTargetStyleString()
    {
        switch (toolTargetStyle)
        {
            case ToolTargetStyle.Enemy:
                return "Any One Enemy";
            case ToolTargetStyle.AllEnemies:
                return "All enemies";
            case ToolTargetStyle.Self:
                return "Self";
            default:
                return "GetToolTargetStyleString ERROR";
        }
    }
    public string GetToolSpecialTagString(ToolSpecialTag toolSpecialTag)
    { 
        switch(toolSpecialTag)
        {
            case ToolSpecialTag.AlwaysAim:
                return "Aim";
            default:
                return "GetToolSpecialTagString ERROR";
        }
    }
    private void DisplayTooltip(Vector2 position, TooltipAlignment alignment)
    {
        List<TooltipData> tooltipDatas = new List<TooltipData>();
        if (damage != 0)
        {
            tooltipDatas.Add(new TooltipData($"{damage} Damage", UIElementType.tooltipDamage));
        }
        tooltipDatas.Add(new TooltipData(GetToolTargetStyleString(), UIElementType.tooltipTargetStyle));
        if(adjacentColumnsTarget > 0)
        {
            tooltipDatas.Add(new TooltipData($"{adjacentColumnsTarget} Range", UIElementType.tooltipSpecial));
        }
        if(areaOfEffectRadius > 0)
        {
            tooltipDatas.Add(new TooltipData($"{areaOfEffectRadius} AOE", UIElementType.tooltipSpecial));
        }
        for(int i = 0; i < toolSpecialTags.Length; i++)
        {
            tooltipDatas.Add(new TooltipData(GetToolSpecialTagString(toolSpecialTags[i]), UIElementType.tooltipSpecial));
        }
        Tooltip.instance.SetupTooltip(position, alignment, tooltipDatas);
    }
    public void SetCardsToSelectIfClicked(List<Card> cards)
    {
        if (cards == null)
        {
            cardsToSelectIfClicked = null;
            SetInteractability(false);
            return;
        }
        SetInteractability(true);
        cardsToSelectIfClicked = cards;
    }
}
/*
    Current available tools:
    One pair, two card straight, two card flush, three of a kind, two pair
 */